name: Mock Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  mock_release:
    if: github.event.pull_request.merged &&
      contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish
      run: |
        echo Simulated release
        echo Current commit $GITHUB_SHA
        git fetch -t
        last=`git describe --abbrev=0 --tags`
        echo $last
        ref=`git show-ref -s $last`
        echo $ref
        git log $ref..$GITHUB_SHA --oneline
