name: Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  publish_release:
    if: github.event.pull_request.merged &&
      contains(github.event.pull_request.labels.*.name, 'release:pending') &&
      startsWith(github.event.pull_request.title, '[chore] Release')

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source for staging
      uses: actions/checkout@v2
      with:
        path: staging

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Prepare release
      id: prepare
      run: ./.github/scripts/prepare_release.sh
      working-directory: staging
      env:
        RETRY_RELEASE: ${{ contains(github.event.pull_request.labels.*.name, 'release:retry') }}
        DRYRUN_RELEASE: ${{ contains(github.event.pull_request.labels.*.name, 'release:dryrun') }}
        SKIP_TWEET: ${{ contains(github.event.pull_request.labels.*.name, 'release:skip-tweet') }}

    - name: Install dependencies
      working-directory: staging
      run: echo Installing dependencies

    - name: Run tests
      if: success() && steps.prepare.outputs.create_tag
      working-directory: staging
      run: |
        echo Running unit tests
        echo Running integration tests

    - name: Generate changelog
      id: changelog
      if: success() && steps.prepare.outputs.create_tag && steps.prepare.outputs.publish
      working-directory: staging
      run: |
        CHANGELOG=`./.github/scripts/generate_changelog.sh`
        echo "$CHANGELOG"
        FILTERED_CHANGELOG=`echo "$CHANGELOG" | grep -v "\\[info\\]"`
        FILTERED_CHANGELOG="${FILTERED_CHANGELOG//'%'/'%25'}"
        FILTERED_CHANGELOG="${FILTERED_CHANGELOG//$'\n'/'%0A'}"
        FILTERED_CHANGELOG="${FILTERED_CHANGELOG//$'\r'/'%0D'}"
        echo "::set-output name=text::${FILTERED_CHANGELOG}"

    - name: Create release tag
      if: success() && steps.prepare.outputs.create_tag && steps.prepare.outputs.publish
      uses: actions/create-release@4d1b6075ce7561b672b8552148edec2f27584fe9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.prepare.outputs.version }}
        release_name: FirCloud ${{ steps.prepare.outputs.version }}
        body: ${{ steps.changelog.outputs.text }}
        draft: false
        prerelease: false

    - name: Checkout source for deployment
      uses: actions/checkout@v2
      if: steps.prepare.outputs.publish || steps.prepare.outputs.reuse_tag
      with:
        ref: ${{ steps.prepare.outputs.version }}
        path: deploy

    - name: Build release artifacts
      working-directory: ${{ steps.prepare.outputs.directory }}
      run: |
        echo Building release artifacts
        mkdir -p dist
        echo Test release > dist/output.txt

    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ${{ steps.prepare.outputs.directory }}/dist

    - name: Publish to Pypi
      if: success() && steps.prepare.outputs.publish
      working-directory: deploy
      run: echo Publishing to Pypi

    - name: Post to Twitter
      if: success() && steps.prepare.outputs.tweet
      run: echo Posting Tweet
