name: Mock Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  mock_release:
    if: github.event.pull_request.merged &&
      contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish
      run: echo Simulated release
