name: Release

on:
  # Only run the workflow when a PR is closed, or when a developer explicitly requests
  # it by sending a 'firebase_build' event.
  pull_request:
    types:
      - closed

  repository_dispatch:
    types:
      - firebase_build

jobs:
  stage_release:
    # If triggered by a PR it must be merged while baring the label 'release:build'.
    if: github.event.action == 'firebase_build' ||
      (github.event.pull_request.merged &&
      contains(github.event.pull_request.labels.*.name, 'release:build'))

    runs-on: ubuntu-latest

    # Checkout source.
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref || github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: echo Installing dependencies

    - name: Run tests
      run: echo Running tests

    - name: Package release artifacts
      run: |
        echo Packaging release artifacts
        mkdir -p dist
        echo Test release > dist/output.txt

    # Attach the packaged artifacts to the workflow output. These can be manually
    # downloaded for later inspection if necessary.
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist

    # Check whether the release should be published. We publish only when the trigger PR is
    #   1. merged
    #   2. to the master branch
    #   3. with a title prefix '[chore] Release '.
    - name: Publish preflight check
      if: success() && github.event.pull_request.merged &&
        github.ref == 'master' &&
        startsWith(github.event.pull_request.title, '[chore] Release ')
      id: prepare
      run: |
        ./.github/scripts/prepare_release.sh
        echo ::set-env name=FIREBASE_PUBLISH::true

    # Tag the release if not executing in the dryrun mode. We pull this action froma
    # custom fork of a contributor until https://github.com/actions/create-release/pull/32
    # is merged. Also note that v1 of this action does not support the "body" parameter.
    - name: Create release tag
      if: success() && env.FIREBASE_PUBLISH
      uses: fleskesvor/create-release@1a72e235c178bf2ae6c51a8ae36febc24568c5fe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.prepare.outputs.version }}
        release_name: FireCloud ${{ steps.prepare.outputs.version }}
        body: ${{ steps.prepare.outputs.changelog }}
        draft: false
        prerelease: false

    # Publish the packaged artifacts to Pypi.
    - name: Publish to Pypi
      if: success() && env.FIREBASE_PUBLISH
      run: echo Publishing to Pypi

    # Post to Twitter if explicitly opted-in.
    - name: Post to Twitter
      if: success() && env.FIREBASE_PUBLISH &&
        contains(github.event.pull_request.labels.*.name, 'release:tweet')
      run: echo Posting Tweet
      continue-on-error: true
