name: Test Conditional
on: repository_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir dist
        echo result > dist/output.txt
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: dist
    - run: |
        ls
        ls dist
        cat dist/output.txt
