# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish Release

on:
  # Only run the workflow when a PR is merged to the master branch.
  pull_request:
    branches: master
    types: closed

jobs:
  publish_release:

    # Check whether the release should be published. We publish only when the trigger PR is
    #   1. merged to the master branch
    #   2. with the label 'release:stage', and
    #   3. the title prefix '[chore] Release '.
    if: github.event.pull_request.merged &&
      contains(github.event.pull_request.labels.*.name, 'release:stage') &&
      startsWith(github.event.pull_request.title, '[chore] Release ')

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source for publish
      uses: actions/checkout@v2

    - name: Install dependencies
      run: echo Installing dependencies

    # Build the Python Wheel and the source distribution.
    - name: Package release artifacts
      run: |
        mkdir -p dist
        echo Hello World > dist/output.txt

    - name: Publish preflight check
      id: preflight
      run: ./.github/scripts/prepare_release.sh
      env:
        COMMITS_URL: ${{ github.event.pull_request.commits_url }}
        COMMENTS_URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # We pull this action from a custom fork of a contributor until
    # https://github.com/actions/create-release/pull/32 is merged. Also note that v1 of
    # this action does not support the "body" parameter.
    - name: Create release tag
      uses: fleskesvor/create-release@1a72e235c178bf2ae6c51a8ae36febc24568c5fe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.preflight.outputs.version }}
        release_name: FireCloud ${{ steps.preflight.outputs.version }}
        body: ${{ steps.preflight.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Publish to Pypi
      run: echo Publishing to Pypi

    # Post to Twitter if explicitly opted-in by adding the label 'release:tweet'.
    - name: Post to Twitter
      if: success() &&
        contains(github.event.pull_request.labels.*.name, 'release:tweet')
      run: echo Posting to Twitter
      continue-on-error: true
